// <auto-generated />
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Hotel_Reservation_Menager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hotel_Reservation_Menager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Hotel_Reservation_Menager.Models.Clients", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("DatabaseGenerated", DatabaseGeneratedOption.Identity)
                    .IsRequired();

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)")
                    .HasAnnotation("DataType", DataType.Text)
                    .HasAnnotation("DisplayName", "First Name");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)")
                    .HasAnnotation("DataType", DataType.Text)
                    .HasAnnotation("DisplayName", "Last Name");

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(10)")
                    .HasAnnotation("DataType", DataType.PhoneNumber)
                    .HasAnnotation("StringLength", 10)
                    .HasAnnotation("DisplayName", "Phone Number");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(30)")
                    .HasAnnotation("DataType", DataType.EmailAddress)
                    .HasAnnotation("StringLength", 30)
                    .HasAnnotation("DisplayName", "Email");

                b.Property<bool>("IsAdult")
                    .IsRequired()
                    .HasAnnotation("DisplayName", "Adult");

                b.HasKey("Id");

                b.ToTable("Clients");
            });

            modelBuilder.Entity("Hotel_Reservation_Menager.Models.Rooms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Capacity")
                    .HasColumnType("int")
                    .IsRequired()
                    .HasAnnotation("DisplayName", "Capacity");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .IsRequired()
                        .HasAnnotation("DisplayName", "Type");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .IsRequired()
                        .HasAnnotation("DisplayName", "Is Available");

                    b.Property<decimal>("PricePerAdult")
                        .HasColumnType("decimal(18,2)")
                        .IsRequired()
                        .HasAnnotation("DisplayName", "Price per Adult");

                    b.Property<decimal>("PricePerChild")
                        .HasColumnType("decimal(18,2)")
                        .IsRequired()
                        .HasAnnotation("DisplayName", "Price per Child");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .IsRequired()
                        .HasAnnotation("DisplayName", "Room Number");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Hotel_Reservation_Menager.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(50)")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasAnnotation("DisplayName", "Username");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(100)")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasAnnotation("DisplayName", "Password");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(50)")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasAnnotation("DisplayName", "First Name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .HasAnnotation("DisplayName", "Middle Name");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .IsRequired()
                        .HasAnnotation("DisplayName", "Last Name");

                    b.Property<string>("Egn")
                        .HasColumnType("nvarchar(max)")
                        .IsRequired()
                        .HasAnnotation("DisplayName", "EGN");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(10)")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasAnnotation("DisplayName", "Phone Number");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasAnnotation("DisplayName", "Email");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2")
                        .IsRequired()
                        .HasAnnotation("DisplayName", "Hire Date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .IsRequired()
                        .HasAnnotation("DisplayName", "Is Active");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("DisplayName", "Termination Date");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
